# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='nome_completo',
            field=models.CharField(default='Nome da Pessoa', max_length=60),
        ),
        migrations.AddField(
            model_name='participante',
            name='sobrenome',
            field=models.CharField(default='Nome sobrenome', max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='nome',
            field=models.CharField(default='Nome sobrenome', max_length=20),
        ),
    ]
