# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='imagem',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
