# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_participante_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='imagem',
            field=models.FileField(upload_to='media/%Y/%m/%d'),
        ),
    ]
