# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171111_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='descricao',
            field=models.CharField(default='descricao do que a pessoa faz na casa', max_length=150),
        ),
    ]
