# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171115_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem_principal',
            field=models.FileField(default='static/imagens/logo_centro.png', upload_to='noticias/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='imagem',
            field=models.FileField(upload_to='participantes/%Y/%m/%d'),
        ),
    ]
