# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_participante_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='perfil',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
