# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171115_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem_principal',
            field=models.FileField(default='logo_centro.png', upload_to='noticias/%Y/%m/%d'),
        ),
    ]
