# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171115_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMes',
            fields=[
                ('cod_evento_mes', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
