# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_eventomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventomes',
            name='data',
            field=models.CharField(default='0000/00/00', max_length=10),
        ),
        migrations.AddField(
            model_name='eventomes',
            name='descricao',
            field=models.CharField(default='Descricao do evento', max_length=700),
        ),
        migrations.AddField(
            model_name='eventomes',
            name='horario',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AddField(
            model_name='eventomes',
            name='local',
            field=models.CharField(default='Local do evento', max_length=100),
        ),
        migrations.AddField(
            model_name='eventomes',
            name='organizador',
            field=models.CharField(default='Organizador do evento', max_length=60),
        ),
        migrations.AddField(
            model_name='eventomes',
            name='titulo',
            field=models.CharField(default='Titulo da noticia', max_length=100, unique=True),
        ),
    ]
